### ISSUE TITLE
Crashmon file access outside Camera folder

### ISSUE THREAD

**Issue by licaon-kter** [afollestad/photo-affix#33]
0.7.1 Xiaomi MIUI11 Android10

```
11-22 10:21:48.392 28277 28277 E AndroidRuntime: FATAL EXCEPTION: main
11-22 10:21:48.392 28277 28277 E AndroidRuntime: Process: com.afollestad.photoaffix, PID: 28277
11-22 10:21:48.392 28277 28277 E AndroidRuntime: java.io.FileNotFoundException: /storage/emulated/0/PhotoAffix BETA/AFFIX_20191122_102148.png: open failed: EACCES (Permission denied)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:496)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at com.afollestad.photoaffix.utilities.RealIoManager.copyUriToFile(IoManager.kt:66)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at com.afollestad.photoaffix.presenters.RealMainPresenter.onExternalPhotoSelected(MainPresenter.kt:60)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at com.afollestad.photoaffix.views.MainActivity$onActivityResult$1$1$selection$1.invokeSuspend(MainActivity.kt:299)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at libcore.io.Linux.open(Native Method)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at android.app.ActivityThread$AndroidOs.open(Unknown Source:15)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:482)
11-22 10:21:48.392 28277 28277 E AndroidRuntime: 	... 10 more
```
...I'd guess this has to do with the new storage access restrictions on Android 10

**Comment by pcsaunak** [comment]
I would like to contribute to the project. Do let me know how can I proceed ?
